# Database Configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
    password: letmein
    driverClassName: com.mysql.cj.jdbc.Driver
